在 try 块之外抛出异常:
    异常处理最有用的属性之一是 throw 语句不必直接放在 try 块中，因为异常在抛出时会向上传播到堆栈。
        这允许我们以更加模块化的方式使用异常处理。

        eg:2-1

展开堆栈:
    让我们重新回顾一下引发异常时会发生什么:
        *首先，程序查看是否可以立即处理异常（这意味着它被抛出在 try 块中）。如果不是，则终止当前函数，程序检查函数的调用者是否会处理异常
            如果不是，它会终止调用者并检查调用者的调用者
            每个函数按顺序终止，直到找到异常处理程序，或者直到 main() 终止而不处理异常。

    eg:202
