Function try blocks：
    *使用函数级 try 块，您必须抛出或重新抛出异常
        如果你没有显式地抛出一个新的异常，或者重新抛出当前的异常（单独使用 throw 关键字），异常将被隐式地重新抛出堆栈。
             eg:4-1

    *函数try块旨在允许您围绕整个函数的主体而不是围绕代码块建立异常处理程序

    *尽管函数级别的 try 块也可以与非成员函数一起使用，但它们通常不会，因为很少有需要这样做的情况。它们几乎只与构造函数一起使用！

    *函数 try 主要用于在将异常向上传递到堆栈之前记录失败，或者用于更改抛出的异常类型。

    *不要使用函数try块清理资源
        当对象的构造失败时，不会调用类的析构函数。因此，您可能很想使用函数 try 块来清理在失败之前已部分分配资源的类
            但是，引用失败对象的成员被认为是未定义的行为，因为在 catch 块执行之前对象是“死的”。
            这意味着你不能在一个类之后使用函数try块清理
            如果要在类后进行清理，请遵循清理抛出异常的类的标准规则