Function try blocks：
    *使用函数级 try 块，您必须抛出或重新抛出异常
        如果你没有显式地抛出一个新的异常，或者重新抛出当前的异常（单独使用 throw 关键字），异常将被隐式地重新抛出堆栈。

    *函数try块旨在允许您围绕整个函数的主体而不是围绕代码块建立异常处理程序
        eg:4-1

    *尽管函数级别的 try 块也可以与非成员函数一起使用，但它们通常不会，因为很少有需要这样做的情况。它们几乎只与构造函数一起使用！